### PR TITLE
RAT-343: Update GitIgnore.java to log root exception while parsing

### PR DESCRIPTION
**Pull request by ottlinger**
Log the underlying IOException the tool ran into while parsing the .gitignore file line by line

### CODE REVIEW

**Comment by ottlinger** [comment]
@nielsbasjes feel free to edit/adapt; PR is only provided while scanning the code.
It seems that GithubAction checks do not run on forks? Would you mind enabling this?

**Comment by nielsbasjes** [comment]
Thanks for the improvement.
I have merged it locally and made some fixes to it.

**Comment by ottlinger** [comment]
@nielsbasjes personally I'd prefer to log the whole exception as this might print out the full stacktrace, so that any consuming application of your library (such as RAT) will have it easier to locate the bug inside of this library and not within RAT. Just my 2ct.

**Comment by nielsbasjes** [comment]
Yes, you are right. I've changed it.

**Comment by nielsbasjes** [comment]
I have just released 1.3.1 with these improvements. Should be in maven central in an hour or so.

**Comment by nielsbasjes** [comment]
@ottlinger Should I put up a merge request to update this or does dependabot handle this?

**Comment by ottlinger** [comment]
Thanks, I guess dependabot will raise a PR, no need for an extra ticket. I will take of it :)

**Pull request closed without merging**
